<Project Sdk="Microsoft.NET.Sdk.Web">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel>
    <RootNamespace>Accounting.Web</RootNamespace>
    <AssetTargetFallback>$(AssetTargetFallback);portable-net45+win8+wp8+wpa81;</AssetTargetFallback>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
    <MvcRazorExcludeRefAssembliesFromPublish>false</MvcRazorExcludeRefAssembliesFromPublish>
    <PreserveCompilationReferences>true</PreserveCompilationReferences>
    <UserSecretsId>83a5c959-a65b-451a-ab84-313045312a85</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\..</DockerfileContext>
  </PropertyGroup>

  <ItemGroup Condition="Exists('./openiddict.pfx')">
    <None Remove="openiddict.pfx" />
    <EmbeddedResource Include="openiddict.pfx">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Logs\**" />
    <Content Remove="Logs\**" />
    <EmbeddedResource Remove="Logs\**" />
    <None Remove="Logs\**" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Pages\**\*.js">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Pages\**\*.css">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <None Remove="Templates\GeneralAccountDataTemplate.xlsx" />
    <None Remove="Templates\SubjectDataTemplate.xlsx" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Templates\GeneralAccountDataTemplate.xlsx">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Templates\GeneralAccountDataTemplateHant.xlsx">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Templates\SubjectDataTemplate.xlsx">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AspNetCore.HealthChecks.UI" Version="9.0.0" />
    <PackageReference Include="AspNetCore.HealthChecks.UI.Client" Version="9.0.0" />
    <PackageReference Include="AspNetCore.HealthChecks.UI.InMemory.Storage" Version="9.0.0" />
    <PackageReference Include="DistributedLock.Redis" Version="1.1.1" />
    <PackageReference Include="DistributedLock.WaitHandles" Version="1.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="10.0.5" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.Async" Version="2.1.0" />
    <PackageReference Include="Volo.Abp.Caching.StackExchangeRedis" Version="10.4.0" />
    <PackageReference Include="Volo.Abp.DistributedLocking" Version="10.4.0" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="10.0.5" />
		<PackageReference Include="Volo.Abp.MailKit" Version="10.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\aspire\Accounting.ServiceDefaults\Accounting.ServiceDefaults.csproj" />
    <ProjectReference Include="..\Accounting.Application\Accounting.Application.csproj" />
    <ProjectReference Include="..\Accounting.HttpApi\Accounting.HttpApi.csproj" />
    <ProjectReference Include="..\Accounting.EntityFrameworkCore\Accounting.EntityFrameworkCore.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.Autofac" Version="10.4.0" />
    <PackageReference Include="Volo.Abp.AspNetCore.Serilog" Version="10.4.0" />
    <PackageReference Include="Volo.Abp.AspNetCore.Authentication.JwtBearer" Version="10.4.0" />
    <PackageReference Include="Volo.Abp.Swashbuckle" Version="10.4.0" />
    <PackageReference Include="Volo.Abp.FeatureManagement.Web" Version="10.4.0" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.AspNetCore.Mvc.UI.Theme.LeptonXLite" Version="5.4.0" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.Account.Web.OpenIddict" Version="10.4.0" />
    <PackageReference Include="Volo.Abp.Identity.Web" Version="10.4.0" />
    <PackageReference Include="Volo.Abp.TenantManagement.Web" Version="10.4.0" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.Studio.Client.AspNetCore" Version="3.0.3" />
  </ItemGroup>

  <ItemGroup>
    <None Include="wwwroot\basicData\currencyModal.js" />
    <None Include="wwwroot\basicData\company.js" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Templates\GeneralAccountDataTemplate.xlsx">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>

</Project>
